# -*- coding: utf-8 -*-

FUTURE_ACCOUNT = 1
SECURITY_ACCOUNT = 2
STOCK_ACCOUNT = SECURITY_ACCOUNT
CREDIT_ACCOUNT = 3
FUTURE_OPTION_ACCOUNT = 5
STOCK_OPTION_ACCOUNT = 6
HUGANGTONG_ACCOUNT = 7
INCOME_SWAP_ACCOUNT = 8
NEW3BOARD_ACCOUNT = 10
SHENGANGTONG_ACCOUNT = 11

ACCOUNT_TYPE_DICT = {
    1: "FUTURE",
    2: "STOCK",
    3: "CREDIT",
    5: "FUTURE_OPTION",
    6: "STOCK_OPTION",
    7: "HUGANGTONG",
    8: "INCOME_SWAP",
    10: "NEW3BOARD",
    11: "SHENGANGTONG",
}

STOCK_BUY = 23
STOCK_SELL = 24
# QMT keeps the SDK credit buy/sell constants numerically aligned with the
# stock constants. The account type, not the value alone, gives them their
# collateral semantics; the bridge converts them to passorder 33/34.
CREDIT_BUY = 23
CREDIT_SELL = 24
CREDIT_FIN_BUY = 27
CREDIT_SLO_SELL = 28

FIX_PRICE = 11
LATEST_PRICE = 5
PRTP_FIX = FIX_PRICE
PRTP_LATEST = LATEST_PRICE
PRTP_MARKET = 12

MARKET_SHANGHAI = "SH"
MARKET_SHENZHEN = "SZ"
MARKET_BEIJING = "BJ"
SH_MARKET = 0
SZ_MARKET = 1
MARKET_ENUM_BEIJING = 70
MARKET_STR_TO_ENUM_MAPPING = {
    "SH": SH_MARKET,
    "SZ": SZ_MARKET,
    "BJ": MARKET_ENUM_BEIJING,
}

MARKET_BEST = 18
MARKET_CANCEL = 19
MARKET_CANCEL_ALL = 20
MARKET_CANCEL_1 = 21
MARKET_CANCEL_5 = 22
MARKET_CONVERT_1 = 23
MARKET_CONVERT_5 = 24
MARKET_PEER_PRICE_FIRST = 44
MARKET_MINE_PRICE_FIRST = 45
MARKET_SZ_INSTBUSI_RESTCANCEL = 46
MARKET_SZ_CONVERT_5_CANCEL = 47
MARKET_SZ_FULL_OR_CANCEL = 48
MARKET_SH_CONVERT_5_CANCEL = 42
MARKET_SH_CONVERT_5_LIMIT = 43

ORDER_REPORTED_CANCEL = 51
ORDER_PARTSUCC_CANCEL = 52
ORDER_PART_CANCEL = 53
ORDER_CANCELED = 54

ACCOUNT_STATUS_OK = 0
ACCOUNT_STATUS_WAITING_LOGIN = 1
ACCOUNT_STATUSING = 2
ACCOUNT_STATUS_FAIL = 3
ACCOUNT_STATUS_INVALID = -1
